# VoteBan Configuration file
# @author syam <admin@sakura-server.net>

#==================#
#   Basic Config   #
#==================#
# Default time for waiting votes (default: 180)
VoteTimeInSeconds: 30
# Accept Percentage (default: 60)
Percentage: 60
# Minimum Players when starting any vote (default: 4)
VoteStartMinPlayers: 4

#====================#
#   Logging Config   #
#====================#
# Default time for waiting votes (default: 180)
LogToFile: true
# LogFilePath
logPath: plugins/VoteBan/vote.log

#=================#
#   Bans Config   #
#=================#
# Set to true for MCBans/glizer global bans. Be sure to follow their guidelines
# (default: false)
GlobalBan: false
# Use fixed BAN reason
UseFixedBanReason: true
BanReason: 'Accepted BAN Vote! (!perc!:!yes!)'
