# VoteBan Configuration file
# @author syam <admin@sakura-server.net>

#==================#
#   Basic Config   #
#==================#
# Default time for waiting votes (default: 180)
VoteTimeInSeconds: 30