##  Plugin Information  ##
name: VoteBan
version: 0.4
main: syam.VoteBan.VoteBan
description: Vote for Banning Griefer!
website: http://sakura-server.net/
softdepend: [MCBans]
##  Original Author     ##
author: syam
commands:
    vote:
      usage: /vote - to see the help
      aliases: [vo]
      description: To see the BanVote help.
permissions:
    voteban.admin:
        default: op
        description: Can administer VoteBan commands.
    voteban.startvote.ban:
        default: op
        description: Can starting Vote for Banning player.
    voteban.startvote.kick:
        default: op
        description: Can starting Vote for Kicking player.