# VoteBan Configuration file
# @author syam <admin@sakura-server.net>

#==================#
#   Basic Config   #
#==================#
# Default time for waiting votes (default: 180)
VoteTimeInSeconds: 180
# Accept Percentage (default: 70)
Percentage: 70.0
# Needs Voter Percentage (default: 25)
NeedsVoterPercentage: 25.0
# Minimum Players when starting any vote (default: 5)
VoteStartMinPlayers: 5

#====================#
#   Logging Config   #
#====================#
# Default time for waiting votes (default: true)
LogToFile: true
# LogFilePath
LogPath: plugins/VoteBan/vote.log

# DetailVoteLog
LogDetail: true
# DetailLogDirectory
DetailDirectory: plugins/VoteBan/detail/

#=================#
#   Bans Config   #
#=================#
# Set to true for MCBans/glizer global bans. Be sure to follow their guidelines
# (default: false)
GlobalBan: false
# Use fixed BAN reason
UseFixedBanReason: true
BanReason: 'Accepted BAN Vote! (!perc!: !yes!)'

#==================#
#   DO NOT TOUCH   #
#==================#
Version: 0.4